# Generated by Django 5.1.4 on 2025-01-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('shoes', 'Shoes'), ('jackets', 'Jackets'), ('sportswear', 'Sportswear'), ('bags', 'Bags'), ('watches', 'Watches')], default='shoes', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
